import Head from 'next/head'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.scss'
import { Main } from '@/components/sections/Main'
import { Busy } from '@reusable-ui/components'
import { dynamicStyleSheets } from '@cssfn/cssfn-react'
import { GenericSection } from '@/components/sections/GenericSection'
import { useGetProductDetailQuery } from '@/store/features/api/apiSlice'
import { formatCurrency } from '@/libs/formatters'
import ImageWithFallback from '@/components/ImageWithFallback'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { Section } from '@/components/sections/Section'



// const inter = Inter({ subsets: ['latin'] })
const useProductDetailStyleSheet = dynamicStyleSheets(
    () => import(/* webpackPrefetch: true */'@/styles/productDetail')
, { id: 'prod-dtl' });



export default function ProductDetail() {
    const styles = useProductDetailStyleSheet();
    const router = useRouter();
    const {data, error, isLoading} = useGetProductDetailQuery(router.query.productPath as any ?? '');
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Main nude={true}>
                <Section className={`${styles.prodDtl} ${isLoading ? 'loading' : ''}`} theme='secondary'>
                    {
                        isLoading
                        ? <Busy theme='primary' size='lg' />
                        : JSON.stringify(data)
                    }
                </Section>
            </Main>
        </>
    )
}
