import Head from 'next/head'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.scss'
import { Main } from '@/components/sections/Main'
import { Busy, Button, Carousel, Group, Input } from '@reusable-ui/components'
import { dynamicStyleSheets } from '@cssfn/cssfn-react'
import { GenericSection } from '@/components/sections/GenericSection'
import { useGetProductDetailQuery } from '@/store/features/api/apiSlice'
import { formatCurrency } from '@/libs/formatters'
import ImageWithFallback from '@/components/ImageWithFallback'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { Section } from '@/components/sections/Section'
import ReactMarkdown from 'react-markdown'



// const inter = Inter({ subsets: ['latin'] })
const useProductDetailStyleSheet = dynamicStyleSheets(
    () => import(/* webpackPrefetch: true */'@/styles/productDetail')
, { id: 'prod-dtl' });



export default function ProductDetail() {
    const styles = useProductDetailStyleSheet();
    const router = useRouter();
    const {data: product, error, isLoading} = useGetProductDetailQuery(router.query.productPath as any ?? '');
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Main nude={true}>
                <Section className={`${styles.prodDtl} ${isLoading ? 'loading' : ''}`} theme='secondary'>
                    {
                        isLoading
                        ? <Busy theme='primary' size='lg' />
                        : <>
                            <section className='images'>
                                <Carousel className='slides' size='lg' theme='primary'>
                                    {product?.images?.map((img: string, index: number) =>
                                        <figure className='img-frame' key={index}>
                                            <ImageWithFallback src={`/products/${product.name}/${img}`} alt={`image #${index + 1} of ${product.name}`} fill={true} priority={true} sizes='100vw' />
                                        </figure>
                                    )}
                                </Carousel>
                            </section>
                            <section className='addToCart'>
                                <h1 className='name h4'>
                                    {product.name}
                                </h1>
                                <span className='price h5'>
                                    {formatCurrency(product.price)}
                                </span>
                                <p>
                                    Quantity:
                                    <Group theme='primary' className='ctrlQty'>
                                        <Button>-</Button>
                                        <Input type='number' min={1} max={9} defaultValue={1} />
                                        <Button>+</Button>
                                    </Group>
                                </p>
                                <p>
                                    <Button theme='primary' className='ctrlAction'>Add to cart</Button>
                                </p>
                            </section>
                            {!!product.description && <section className='desc'>
                                <ReactMarkdown>
                                    {product.description}
                                </ReactMarkdown>
                            </section>}
                        </>
                    }
                </Section>
            </Main>
        </>
    )
}
