import Head from 'next/head'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.scss'
import { Main } from '@/components/sections/Main'
import { Busy } from '@reusable-ui/components'
import { dynamicStyleSheets } from '@cssfn/cssfn-react'
import { GenericSection } from '@/components/sections/GenericSection'
import { useGetProductListQuery } from '@/store/features/api/apiSlice'
import { formatCurrency } from '@/libs/formatters'
import ImageWithFallback from '@/components/ImageWithFallback'
import Link from 'next/link'



// const inter = Inter({ subsets: ['latin'] })
const useProductListStyleSheet = dynamicStyleSheets(
    () => import(/* webpackPrefetch: true */'@/styles/productList')
, { id: 'prod-list' });



export default function ProductList() {
    const styles = useProductListStyleSheet();
    const {data, error, isLoading} = useGetProductListQuery();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Main nude={true}>
                <GenericSection className={`${styles.list} ${isLoading ? 'loading' : ''}`} theme='secondary'>
                    {
                        isLoading
                        ? <Busy theme='primary' size='lg' />
                        : data?.map((product) =>
                            <article key={product._id}>
                                <figure>
                                    <ImageWithFallback alt={product.name ?? ''} src={product.images?.[0] ? `/products/${product.name}/${product.images?.[0]}` : undefined} fill={true} sizes='414px' />
                                </figure>
                                <header>
                                    <h2 className='name h6'>
                                        {product.name}
                                    </h2>
                                    <span className='price h6'>
                                        {formatCurrency(product.price)}
                                    </span>
                                </header>
                                <Link href={`/products/${product.path}`} />
                            </article>
                        )
                    }
                </GenericSection>
            </Main>
        </>
    )
}
