export const stateCityToIdMap = new Map<string, string>([
    ['aceh/banda aceh', '20'],
    ['aceh/bireun', '72'],
    ['aceh/kabupaten aceh barat', '1'],
    ['aceh/kabupaten aceh barat daya', '2'],
    ['aceh/kabupaten aceh besar', '3'],
    ['aceh/kabupaten aceh jaya', '4'],
    ['aceh/kabupaten aceh selatan', '5'],
    ['aceh/kabupaten aceh singkil', '6'],
    ['aceh/kabupaten aceh tamiang', '7'],
    ['aceh/kabupaten aceh tengah', '8'],
    ['aceh/kabupaten aceh tenggara', '9'],
    ['aceh/kabupaten aceh timur', '10'],
    ['aceh/kabupaten aceh utara', '11'],
    ['aceh/kabupaten bener meriah', '59'],
    ['aceh/kabupaten gayo lues', '127'],
    ['aceh/kabupaten nagan raya', '300'],
    ['aceh/kabupaten pidie', '358'],
    ['aceh/kabupaten simeulue', '414'],
    ['aceh/kota banda aceh', '20'],
    ['aceh/kota langsa', '230'],
    ['aceh/kota lhokseumawe', '235'],
    ['aceh/kota sabang', '384'],
    ['aceh/kota subulussalam', '429'],
    ['aceh/langsa', '230'],
    ['aceh/lhokseumawe', '235'],
    ['aceh/sabang', '384'],
    ['bali/denpasar', '114'],
    ['bali/kabupaten badung', '17'],
    ['bali/kabupaten bangli', '32'],
    ['bali/kabupaten buleleng', '94'],
    ['bali/kabupaten gianyar', '128'],
    ['bali/kabupaten jembrana', '161'],
    ['bali/kabupaten karang asem', '170'],
    ['bali/kabupaten klungkung', '197'],
    ['bali/kabupaten tabanan', '447'],
    ['bali/klungkung', '197'],
    ['bali/kota denpasar', '114'],
    ['bali/tabanan', '447'],
    ['banten/kabupaten lebak', '232'],
    ['banten/kabupaten pandeglang', '331'],
    ['banten/kabupaten serang', '403'],
    ['banten/kabupaten tangerang', '456'],
    ['banten/kota cilegon', '106'],
    ['banten/kota serang', '403'],
    ['banten/kota tangerang', '456'],
    ['banten/kota tangerang selatan', '457'],
    ['banten/pandeglang', '331'],
    ['banten/serang', '403'],
    ['banten/tangerang', '456'],
    ['bengkulu/bengkulu', '62'],
    ['bengkulu/kabupaten bengkulu selatan', '63'],
    ['bengkulu/kabupaten bengkulu tengah', '64'],
    ['bengkulu/kabupaten bengkulu utara', '65'],
    ['bengkulu/kabupaten kaur', '175'],
    ['bengkulu/kabupaten kepahiang', '183'],
    ['bengkulu/kabupaten lebong', '233'],
    ['bengkulu/kabupaten mukomuko', '294'],
    ['bengkulu/kabupaten rejang lebong', '379'],
    ['bengkulu/kabupaten seluma', '397'],
    ['bengkulu/kota bengkulu', '62'],
    ['di yogyakarta/bantul', '39'],
    ['di yogyakarta/kabupaten bantul', '39'],
    ['di yogyakarta/kabupaten gunung kidul', '135'],
    ['di yogyakarta/kabupaten kulon progo', '210'],
    ['di yogyakarta/kabupaten sleman', '419'],
    ['di yogyakarta/kota yogyakarta', '501'],
    ['di yogyakarta/sleman', '419'],
    ['di yogyakarta/yogyakarta', '501'],
    ['dki jakarta/kota administrasi jakarta barat', '151'],
    ['dki jakarta/kota administrasi jakarta pusat', '152'],
    ['dki jakarta/kota administrasi jakarta selatan', '153'],
    ['dki jakarta/kota administrasi jakarta timur', '154'],
    ['dki jakarta/kota administrasi jakarta utara', '155'],
    ['gorontalo/gorontalo', '130'],
    ['gorontalo/kabupaten boalemo', '77'],
    ['gorontalo/kabupaten bone bolango', '88'],
    ['gorontalo/kabupaten gorontalo', '130'],
    ['gorontalo/kabupaten gorontalo utara', '131'],
    ['gorontalo/kabupaten pohuwato', '361'],
    ['gorontalo/kota gorontalo', '130'],
    ['jambi/kabupaten batang hari', '50'],
    ['jambi/kabupaten bungo', '97'],
    ['jambi/kabupaten kerinci', '194'],
    ['jambi/kabupaten merangin', '280'],
    ['jambi/kabupaten muaro jambi', '293'],
    ['jambi/kabupaten sarolangun', '393'],
    ['jambi/kabupaten tanjung jabung barat', '460'],
    ['jambi/kabupaten tanjung jabung timur', '461'],
    ['jambi/kabupaten tebo', '471'],
    ['jambi/kota jambi', '156'],
    ['jambi/kota sungai penuh', '442'],
    ['jambi/sungai penuh', '442'],
    ['jawa barat/bandung', '23'],
    ['jawa barat/banjar', '34'],
    ['jawa barat/bekasi', '55'],
    ['jawa barat/bogor', '79'],
    ['jawa barat/ciamis', '103'],
    ['jawa barat/cimahi', '107'],
    ['jawa barat/cirebon', '109'],
    ['jawa barat/depok', '115'],
    ['jawa barat/indramayu', '149'],
    ['jawa barat/kabupaten bandung', '23'],
    ['jawa barat/kabupaten bandung barat', '24'],
    ['jawa barat/kabupaten bekasi', '55'],
    ['jawa barat/kabupaten bogor', '79'],
    ['jawa barat/kabupaten ciamis', '103'],
    ['jawa barat/kabupaten cianjur', '104'],
    ['jawa barat/kabupaten cirebon', '109'],
    ['jawa barat/kabupaten garut', '126'],
    ['jawa barat/kabupaten indramayu', '149'],
    ['jawa barat/kabupaten karawang', '171'],
    ['jawa barat/kabupaten kuningan', '211'],
    ['jawa barat/kabupaten majalengka', '252'],
    ['jawa barat/kabupaten pangandaran', '332'],
    ['jawa barat/kabupaten purwakarta', '376'],
    ['jawa barat/kabupaten subang', '428'],
    ['jawa barat/kabupaten sukabumi', '431'],
    ['jawa barat/kabupaten sumedang', '440'],
    ['jawa barat/kabupaten tasikmalaya', '469'],
    ['jawa barat/kota bandung', '23'],
    ['jawa barat/kota banjar', '34'],
    ['jawa barat/kota bekasi', '55'],
    ['jawa barat/kota bogor', '79'],
    ['jawa barat/kota cimahi', '107'],
    ['jawa barat/kota cirebon', '109'],
    ['jawa barat/kota depok', '115'],
    ['jawa barat/kota sukabumi', '431'],
    ['jawa barat/kota tasikmalaya', '469'],
    ['jawa barat/kuningan', '211'],
    ['jawa barat/majalengka', '252'],
    ['jawa barat/purwakarta', '376'],
    ['jawa barat/sukabumi', '431'],
    ['jawa barat/sumedang', '440'],
    ['jawa barat/tasikmalaya', '469'],
    ['jawa tengah/banyumas', '41'],
    ['jawa tengah/batang', '49'],
    ['jawa tengah/blora', '76'],
    ['jawa tengah/boyolali', '91'],
    ['jawa tengah/demak', '113'],
    ['jawa tengah/kabupaten banjarnegara', '37'],
    ['jawa tengah/kabupaten banyumas', '41'],
    ['jawa tengah/kabupaten batang', '49'],
    ['jawa tengah/kabupaten blora', '76'],
    ['jawa tengah/kabupaten boyolali', '91'],
    ['jawa tengah/kabupaten brebes', '92'],
    ['jawa tengah/kabupaten cilacap', '105'],
    ['jawa tengah/kabupaten demak', '113'],
    ['jawa tengah/kabupaten grobogan', '134'],
    ['jawa tengah/kabupaten jepara', '163'],
    ['jawa tengah/kabupaten karanganyar', '169'],
    ['jawa tengah/kabupaten kebumen', '177'],
    ['jawa tengah/kabupaten kendal', '181'],
    ['jawa tengah/kabupaten klaten', '196'],
    ['jawa tengah/kabupaten kudus', '209'],
    ['jawa tengah/kabupaten magelang', '250'],
    ['jawa tengah/kabupaten pati', '344'],
    ['jawa tengah/kabupaten pekalongan', '349'],
    ['jawa tengah/kabupaten pemalang', '352'],
    ['jawa tengah/kabupaten purbalingga', '375'],
    ['jawa tengah/kabupaten purworejo', '377'],
    ['jawa tengah/kabupaten rembang', '380'],
    ['jawa tengah/kabupaten semarang', '399'],
    ['jawa tengah/kabupaten sragen', '427'],
    ['jawa tengah/kabupaten sukoharjo', '433'],
    ['jawa tengah/kabupaten tegal', '473'],
    ['jawa tengah/kabupaten temanggung', '476'],
    ['jawa tengah/kabupaten wonogiri', '497'],
    ['jawa tengah/kabupaten wonosobo', '498'],
    ['jawa tengah/klaten', '196'],
    ['jawa tengah/kota magelang', '250'],
    ['jawa tengah/kota pekalongan', '349'],
    ['jawa tengah/kota salatiga', '386'],
    ['jawa tengah/kota semarang', '399'],
    ['jawa tengah/kota surakarta', '445'],
    ['jawa tengah/kota tegal', '473'],
    ['jawa tengah/kudus', '209'],
    ['jawa tengah/magelang', '250'],
    ['jawa tengah/pati', '344'],
    ['jawa tengah/pekalongan', '349'],
    ['jawa tengah/pemalang', '352'],
    ['jawa tengah/purbalingga', '375'],
    ['jawa tengah/salatiga', '386'],
    ['jawa tengah/semarang', '399'],
    ['jawa tengah/sragen', '427'],
    ['jawa tengah/surakarta', '445'],
    ['jawa tengah/tegal', '473'],
    ['jawa tengah/wonosobo', '498'],
    ['jawa timur/bangkalan', '31'],
    ['jawa timur/banyuwangi', '42'],
    ['jawa timur/batu', '51'],
    ['jawa timur/blitar', '75'],
    ['jawa timur/bojonegoro', '80'],
    ['jawa timur/bondowoso', '86'],
    ['jawa timur/gresik', '133'],
    ['jawa timur/jember', '160'],
    ['jawa timur/jombang', '164'],
    ['jawa timur/kabupaten bangkalan', '31'],
    ['jawa timur/kabupaten banyuwangi', '42'],
    ['jawa timur/kabupaten blitar', '75'],
    ['jawa timur/kabupaten bojonegoro', '80'],
    ['jawa timur/kabupaten bondowoso', '86'],
    ['jawa timur/kabupaten jember', '160'],
    ['jawa timur/kabupaten jombang', '164'],
    ['jawa timur/kabupaten kediri', '179'],
    ['jawa timur/kabupaten lamongan', '222'],
    ['jawa timur/kabupaten lumajang', '243'],
    ['jawa timur/kabupaten madiun', '248'],
    ['jawa timur/kabupaten magetan', '251'],
    ['jawa timur/kabupaten malang', '256'],
    ['jawa timur/kabupaten mojokerto', '290'],
    ['jawa timur/kabupaten nganjuk', '305'],
    ['jawa timur/kabupaten ngawi', '306'],
    ['jawa timur/kabupaten pacitan', '317'],
    ['jawa timur/kabupaten pamekasan', '330'],
    ['jawa timur/kabupaten pasuruan', '343'],
    ['jawa timur/kabupaten ponorogo', '363'],
    ['jawa timur/kabupaten probolinggo', '370'],
    ['jawa timur/kabupaten sampang', '390'],
    ['jawa timur/kabupaten sidoarjo', '409'],
    ['jawa timur/kabupaten situbondo', '418'],
    ['jawa timur/kabupaten sumenep', '441'],
    ['jawa timur/kabupaten trenggalek', '487'],
    ['jawa timur/kabupaten tuban', '489'],
    ['jawa timur/kabupaten tulungagung', '492'],
    ['jawa timur/kediri', '179'],
    ['jawa timur/kota batu', '51'],
    ['jawa timur/kota blitar', '75'],
    ['jawa timur/kota kediri', '179'],
    ['jawa timur/kota madiun', '248'],
    ['jawa timur/kota malang', '256'],
    ['jawa timur/kota mojokerto', '290'],
    ['jawa timur/kota pasuruan', '343'],
    ['jawa timur/kota probolinggo', '370'],
    ['jawa timur/kota surabaya', '444'],
    ['jawa timur/lamongan', '222'],
    ['jawa timur/lumajang', '243'],
    ['jawa timur/madiun', '248'],
    ['jawa timur/malang', '256'],
    ['jawa timur/mojokerto', '290'],
    ['jawa timur/nganjuk', '305'],
    ['jawa timur/pamekasan', '330'],
    ['jawa timur/pasuruan', '343'],
    ['jawa timur/ponorogo', '363'],
    ['jawa timur/probolinggo', '370'],
    ['jawa timur/sampang', '390'],
    ['jawa timur/sidoarjo', '409'],
    ['jawa timur/situbondo', '418'],
    ['jawa timur/sumenep', '441'],
    ['jawa timur/surabaya', '444'],
    ['jawa timur/trenggalek', '487'],
    ['jawa timur/tuban', '489'],
    ['jawa timur/tulungagung', '492'],
    ['kalimantan barat/kabupaten bengkayang', '61'],
    ['kalimantan barat/kabupaten kapuas hulu', '168'],
    ['kalimantan barat/kabupaten kayong utara', '176'],
    ['kalimantan barat/kabupaten ketapang', '195'],
    ['kalimantan barat/kabupaten kubu raya', '208'],
    ['kalimantan barat/kabupaten landak', '228'],
    ['kalimantan barat/kabupaten melawi', '279'],
    ['kalimantan barat/kabupaten sambas', '388'],
    ['kalimantan barat/kabupaten sanggau', '391'],
    ['kalimantan barat/kabupaten sekadau', '395'],
    ['kalimantan barat/kabupaten sintang', '417'],
    ['kalimantan barat/kota pontianak', '365'],
    ['kalimantan barat/kota singkawang', '415'],
    ['kalimantan selatan/banjarmasin', '36'],
    ['kalimantan selatan/kabupaten balangan', '18'],
    ['kalimantan selatan/kabupaten banjar', '33'],
    ['kalimantan selatan/kabupaten barito kuala', '43'],
    ['kalimantan selatan/kabupaten hulu sungai selatan', '143'],
    ['kalimantan selatan/kabupaten hulu sungai tengah', '144'],
    ['kalimantan selatan/kabupaten hulu sungai utara', '145'],
    ['kalimantan selatan/kabupaten kota baru', '203'],
    ['kalimantan selatan/kabupaten tabalong', '446'],
    ['kalimantan selatan/kabupaten tanah bumbu', '452'],
    ['kalimantan selatan/kabupaten tanah laut', '454'],
    ['kalimantan selatan/kabupaten tapin', '466'],
    ['kalimantan selatan/kota banjar baru', '35'],
    ['kalimantan selatan/kota banjarmasin', '36'],
    ['kalimantan tengah/kabupaten barito selatan', '44'],
    ['kalimantan tengah/kabupaten barito timur', '45'],
    ['kalimantan tengah/kabupaten barito utara', '46'],
    ['kalimantan tengah/kabupaten gunung mas', '136'],
    ['kalimantan tengah/kabupaten kapuas', '167'],
    ['kalimantan tengah/kabupaten katingan', '174'],
    ['kalimantan tengah/kabupaten kotawaringin barat', '205'],
    ['kalimantan tengah/kabupaten kotawaringin timur', '206'],
    ['kalimantan tengah/kabupaten lamandau', '221'],
    ['kalimantan tengah/kabupaten murung raya', '296'],
    ['kalimantan tengah/kabupaten pulang pisau', '371'],
    ['kalimantan tengah/kabupaten seruyan', '405'],
    ['kalimantan tengah/kabupaten sukamara', '432'],
    ['kalimantan tengah/kota palangka raya', '326'],
    ['kalimantan timur/balikpapan', '19'],
    ['kalimantan timur/bontang', '89'],
    ['kalimantan timur/kabupaten berau', '66'],
    ['kalimantan timur/kabupaten kutai barat', '214'],
    ['kalimantan timur/kabupaten kutai kartanegara', '215'],
    ['kalimantan timur/kabupaten kutai timur', '216'],
    ['kalimantan timur/kabupaten paser', '341'],
    ['kalimantan timur/kabupaten penajam paser utara', '354'],
    ['kalimantan timur/kota balikpapan', '19'],
    ['kalimantan timur/kota bontang', '89'],
    ['kalimantan timur/kota samarinda', '387'],
    ['kalimantan timur/samarinda', '387'],
    ['kalimantan utara/kabupaten bulungan', '96'],
    ['kalimantan utara/kabupaten malinau', '257'],
    ['kalimantan utara/kabupaten nunukan', '311'],
    ['kalimantan utara/kabupaten tana tidung', '450'],
    ['kalimantan utara/tarakan', '467'],
    ['kepulauan bangka belitung/kabupaten bangka', '27'],
    ['kepulauan bangka belitung/kabupaten bangka barat', '28'],
    ['kepulauan bangka belitung/kabupaten bangka selatan', '29'],
    ['kepulauan bangka belitung/kabupaten bangka tengah', '30'],
    ['kepulauan bangka belitung/kabupaten belitung', '56'],
    ['kepulauan bangka belitung/kabupaten belitung timur', '57'],
    ['kepulauan bangka belitung/kota pangkal pinang', '334'],
    ['kepulauan riau/kabupaten bintan', '71'],
    ['kepulauan riau/kabupaten karimun', '172'],
    ['kepulauan riau/kabupaten kepulauan anambas', '184'],
    ['kepulauan riau/kabupaten lingga', '237'],
    ['kepulauan riau/kabupaten natuna', '302'],
    ['kepulauan riau/kota batam', '48'],
    ['kepulauan riau/kota tanjung pinang', '462'],
    ['kepulauan riau/tanjung pinang', '462'],
    ['lampung/bandar lampung', '21'],
    ['lampung/kabupaten lampung barat', '223'],
    ['lampung/kabupaten lampung selatan', '224'],
    ['lampung/kabupaten lampung tengah', '225'],
    ['lampung/kabupaten lampung timur', '226'],
    ['lampung/kabupaten lampung utara', '227'],
    ['lampung/kabupaten mesuji', '282'],
    ['lampung/kabupaten pesawaran', '355'],
    ['lampung/kabupaten pesisir barat', '356'],
    ['lampung/kabupaten pringsewu', '368'],
    ['lampung/kabupaten tanggamus', '458'],
    ['lampung/kabupaten tulangbawang', '490'],
    ['lampung/kabupaten way kanan', '496'],
    ['lampung/kota bandar lampung', '21'],
    ['lampung/kota metro', '283'],
    ['lampung/metro', '283'],
    ['maluku utara/kabupaten halmahera barat', '138'],
    ['maluku utara/kabupaten halmahera selatan', '139'],
    ['maluku utara/kabupaten halmahera tengah', '140'],
    ['maluku utara/kabupaten halmahera utara', '142'],
    ['maluku utara/kabupaten kepulauan sula', '191'],
    ['maluku utara/kabupaten pulau morotai', '372'],
    ['maluku utara/kota ternate', '477'],
    ['maluku utara/kota tidore kepulauan', '478'],
    ['maluku utara/ternate', '477'],
    ['maluku/ambon', '14'],
    ['maluku/kabupaten buru', '99'],
    ['maluku/kabupaten buru selatan', '100'],
    ['maluku/kabupaten kepulauan aru', '185'],
    ['maluku/kabupaten maluku barat daya', '258'],
    ['maluku/kabupaten maluku tengah', '259'],
    ['maluku/kabupaten maluku tenggara', '260'],
    ['maluku/kabupaten maluku tenggara barat', '261'],
    ['maluku/kabupaten seram bagian barat', '400'],
    ['maluku/kabupaten seram bagian timur', '401'],
    ['maluku/kota ambon', '14'],
    ['maluku/kota tual', '488'],
    ['maluku/tual', '488'],
    ['nusa tenggara barat/bima', '69'],
    ['nusa tenggara barat/dompu', '118'],
    ['nusa tenggara barat/kabupaten bima', '69'],
    ['nusa tenggara barat/kabupaten dompu', '118'],
    ['nusa tenggara barat/kabupaten lombok barat', '238'],
    ['nusa tenggara barat/kabupaten lombok tengah', '239'],
    ['nusa tenggara barat/kabupaten lombok timur', '240'],
    ['nusa tenggara barat/kabupaten lombok utara', '241'],
    ['nusa tenggara barat/kabupaten sumbawa', '438'],
    ['nusa tenggara barat/kabupaten sumbawa barat', '439'],
    ['nusa tenggara barat/kota bima', '69'],
    ['nusa tenggara barat/kota mataram', '276'],
    ['nusa tenggara barat/mataram', '276'],
    ['nusa tenggara timur/ende', '122'],
    ['nusa tenggara timur/kabupaten alor', '13'],
    ['nusa tenggara timur/kabupaten belu', '58'],
    ['nusa tenggara timur/kabupaten ende', '122'],
    ['nusa tenggara timur/kabupaten flores timur', '125'],
    ['nusa tenggara timur/kabupaten kupang', '213'],
    ['nusa tenggara timur/kabupaten lembata', '234'],
    ['nusa tenggara timur/kabupaten manggarai', '269'],
    ['nusa tenggara timur/kabupaten manggarai barat', '270'],
    ['nusa tenggara timur/kabupaten manggarai timur', '271'],
    ['nusa tenggara timur/kabupaten nagekeo', '301'],
    ['nusa tenggara timur/kabupaten ngada', '304'],
    ['nusa tenggara timur/kabupaten rote ndao', '383'],
    ['nusa tenggara timur/kabupaten sabu raijua', '385'],
    ['nusa tenggara timur/kabupaten sikka', '412'],
    ['nusa tenggara timur/kabupaten sumba barat', '434'],
    ['nusa tenggara timur/kabupaten sumba barat daya', '435'],
    ['nusa tenggara timur/kabupaten sumba tengah', '436'],
    ['nusa tenggara timur/kabupaten sumba timur', '437'],
    ['nusa tenggara timur/kabupaten timor tengah selatan', '479'],
    ['nusa tenggara timur/kabupaten timor tengah utara', '480'],
    ['nusa tenggara timur/kota kupang', '213'],
    ['nusa tenggara timur/kupang', '213'],
    ['papua barat/kabupaten fakfak', '124'],
    ['papua barat/kabupaten kaimana', '165'],
    ['papua barat/kabupaten manokwari', '272'],
    ['papua barat/kabupaten manokwari selatan', '273'],
    ['papua barat/kabupaten maybrat', '277'],
    ['papua barat/kabupaten raja ampat', '378'],
    ['papua barat/kabupaten sorong', '425'],
    ['papua barat/kabupaten sorong selatan', '426'],
    ['papua barat/kabupaten tambrauw', '449'],
    ['papua barat/kabupaten teluk bintuni', '474'],
    ['papua barat/kabupaten teluk wondama', '475'],
    ['papua barat/kota sorong', '425'],
    ['papua barat/manokwari', '272'],
    ['papua barat/sorong', '425'],
    ['papua/jayapura', '158'],
    ['papua/kabupaten asmat', '16'],
    ['papua/kabupaten biak numfor', '67'],
    ['papua/kabupaten boven digoel', '90'],
    ['papua/kabupaten deiyai', '111'],
    ['papua/kabupaten dogiyai', '117'],
    ['papua/kabupaten intan jaya', '150'],
    ['papua/kabupaten jayapura', '158'],
    ['papua/kabupaten jayawijaya', '159'],
    ['papua/kabupaten keerom', '180'],
    ['papua/kabupaten kepulauan yapen', '193'],
    ['papua/kabupaten lanny jaya', '231'],
    ['papua/kabupaten mamberamo raya', '263'],
    ['papua/kabupaten mamberamo tengah', '264'],
    ['papua/kabupaten mappi', '274'],
    ['papua/kabupaten merauke', '281'],
    ['papua/kabupaten mimika', '284'],
    ['papua/kabupaten nabire', '299'],
    ['papua/kabupaten nduga', '303'],
    ['papua/kabupaten paniai', '335'],
    ['papua/kota jayapura', '158'],
    ['papua/nabire', '299'],
]);
