import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { Main } from '@/components/sections/Main'
import { HeroSection } from '@/components/sections/HeroSection'
import { Section } from '@/components/sections/Section'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Main nude={true}>
                <HeroSection theme='primary' className={styles.hero}>
                    <h1 className='display-4'>Reusable-UI</h1>
                    <p className='display-6'>Reuse the components,<br />save your time now and next</p>
                    <div className='actions'>
                    </div>
                </HeroSection>
                <Section className={styles.features}>
                </Section>
            </Main>
        </>
    )
}
