import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { Main } from '@/components/sections/Main'
import { HeroSection } from '@/components/sections/HeroSection'
import { Section } from '@/components/sections/Section'
import { Container } from '@reusable-ui/components'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Main nude={true}>
                <HeroSection theme='primary' className={styles.hero}>
                    {/* <Image alt='ART Etcnic Swimwear' src='/artswimwear.svg' width={48*4} height={40*4} /> */}
                    <Container tag='footer' className='fill' theme='primary' mild={false} gradient={true}>
                        blah
                    </Container>
                </HeroSection>
                <Section className={styles.features}>
                    <p>
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque saepe vitae nemo, veniam quos voluptates ducimus dolorem et incidunt odio possimus sint illum excepturi maxime quisquam ratione ut facere sed?
                    </p>
                </Section>
            </Main>
        </>
    )
}
