import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { Main } from '@/components/sections/Main'
import { HeroSection } from '@/components/sections/HeroSection'
import { Section } from '@/components/sections/Section'
import { AccordionItem, Button, Container, ExclusiveAccordion, Icon } from '@reusable-ui/components'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Main nude={true}>
                <HeroSection theme='secondary' className={styles.hero}>
                    {/* <Image alt='ART Etcnic Swimwear' src='/artswimwear.svg' width={48*4} height={40*4} /> */}
                    <Container tag='footer' className='fill' theme='primary' mild={false} gradient={true}>
                        <Icon className='scroller' icon='scrolldown' size='xl' />
                        {/* <span className='hint'>Scroll down to see more.</span> */}
                    </Container>
                </HeroSection>
                <Section className={styles.features} title='Our Story' theme='secondary'>
                    <div className='figures'>
                        <figure>
                            <Image alt='Atika Paramita' src='/figures/atika.jpg' width={200} height={200} />
                            <figcaption>
                                <h3>
                                    Atika Paramita
                                </h3>
                                <Button buttonStyle='link' theme='primary' size='sm' href='https://www.instagram.com/atikapj'>@ATIKAPJ</Button>
                            </figcaption>
                        </figure>
                        <figure>
                            <Image alt='Rossalia Tomlinson' src='/figures/rossalia.jpg' width={200} height={200} />
                            <figcaption>
                                <h3>
                                    Rossalia Tomlinson
                                </h3>
                                <Button buttonStyle='link' theme='primary' size='sm' href='https://www.instagram.com/rossaliauran'>@ROSSALIAURAN</Button>
                            </figcaption>
                        </figure>
                    </div>
                    <p>
                        ART is an acronym for Atika and Rossalia Tomlinson, they are best friends from
                        high school. In 2019, they decided to follow their dreams and launch ART – their
                        own sustainable swimwear brand. Their vision was to create a reversible swimwear
                        range by combining eco friendly materials with various Indonesian batik and
                        weaving designs.
                    </p>
                    <p>
                        Both Atika and Rossalia are passionate about the conservation of Indonesia’s
                        beautiful oceans, beaches and communities. The girls wanted ART to team up with
                        Art and Nature community whose aim is to empower the people of Indonesia with
                        the skills and education needed to integrate sustainability into their communities
                    </p>
                    <p>
                        In conclusion, by introducing ART ethnic swimwear to the world stage we all really
                        can be “<strong>At one with ART and nature.</strong>”
                    </p>
                </Section>
                <Section className={styles.fabrics} title='Eco-friendly fabrics' theme='primary'>
                    <p>
                        Sustainability and being eco-friendly is fully integrated into our strategy.
                    </p>
                    <p>
                        We proudly use VITA fabric, made with
                        Econyl® regenerated nylon from made
                        from abandoned fishing nets and
                        REPREVE® made from recycled plastic in
                        our swimwear production.
                    </p>
                    <Section className={styles.howWorks} title='How does it work?'>
                        <ExclusiveAccordion defaultExpandedListIndex={0} theme='primary'>
                            <AccordionItem label='Collecting'>
                                <div className='how-work-item'>
                                    <p>
                                        Ghost fishing nets and plastic waste
                                        are collected around the globe through
                                        different initiatives such as Healthy Seas.
                                        From 2013 to 2018, they collected 453
                                        tons of fishing nets, which equals the
                                        weight of three blue whales!
                                    </p>
                                    <Image alt='' src='/illus/turtle.jpg' width={200*1.5} height={200} />
                                </div>
                            </AccordionItem>
                            <AccordionItem label='Recycling'>
                                <div className='how-work-item'>
                                    <p>
                                        The material is then transformed back
                                        to its original purity after a regeneration
                                        process.
                                        The yarn is blended with Lycra® Xtra
                                        Life™ to ensure optimal support while
                                        remaining soft and stretchy.
                                        Our swimwear is UV protective, and
                                        highly resistant to chlorine, sun creams
                                        and oils.
                                    </p>
                                    <Image alt='' src='/illus/particles.jpg' width={200*1.5} height={200} />
                                </div>
                            </AccordionItem>
                        </ExclusiveAccordion>
                    </Section>
                </Section>
            </Main>
        </>
    )
}
