export const stateCityToIdMap = new Map<string, string>([
    [ "aceh/aceh barat daya", "2" ],
    [ "aceh/aceh barat", "1" ],
    [ "aceh/aceh besar", "3" ],
    [ "aceh/aceh jaya", "4" ],
    [ "aceh/aceh selatan", "5" ],
    [ "aceh/aceh singkil", "6" ],
    [ "aceh/aceh tamiang", "7" ],
    [ "aceh/aceh tengah", "8" ],
    [ "aceh/aceh tenggara", "9" ],
    [ "aceh/aceh timur", "10" ],
    [ "aceh/aceh utara", "11" ],
    [ "aceh/banda aceh", "20" ],
    [ "aceh/bener meriah", "59" ],
    [ "aceh/bireun", "72" ],
    [ "aceh/gayo lues", "127" ],
    [ "aceh/langsa", "230" ],
    [ "aceh/lhokseumawe", "235" ],
    [ "aceh/nagan raya", "300" ],
    [ "aceh/pidie jaya", "359" ],
    [ "aceh/pidie", "358" ],
    [ "aceh/sabang", "384" ],
    [ "aceh/simeulue", "414" ],
    [ "aceh/subulussalam", "429" ],
    [ "bali/badung", "17" ],
    [ "bali/bangli", "32" ],
    [ "bali/buleleng", "94" ],
    [ "bali/denpasar", "114" ],
    [ "bali/gianyar", "128" ],
    [ "bali/jembrana", "161" ],
    [ "bali/karang asem", "170" ],
    [ "bali/klungkung", "197" ],
    [ "bali/tabanan", "447" ],
    [ "kepulauan bangka belitung/bangka barat", "28" ],
    [ "kepulauan bangka belitung/bangka selatan", "29" ],
    [ "kepulauan bangka belitung/bangka tengah", "30" ],
    [ "kepulauan bangka belitung/bangka", "27" ],
    [ "kepulauan bangka belitung/belitung timur", "57" ],
    [ "kepulauan bangka belitung/belitung", "56" ],
    [ "kepulauan bangka belitung/pangkal pinang", "334" ],
    [ "banten/cilegon", "106" ],
    [ "banten/lebak", "232" ],
    [ "banten/pandeglang", "331" ],
    [ "banten/serang", "403" ],
    [ "banten/tangerang selatan", "457" ],
    [ "banten/tangerang", "456" ],
    [ "bengkulu/bengkulu selatan", "63" ],
    [ "bengkulu/bengkulu tengah", "64" ],
    [ "bengkulu/bengkulu utara", "65" ],
    [ "bengkulu/bengkulu", "62" ],
    [ "bengkulu/kaur", "175" ],
    [ "bengkulu/kepahiang", "183" ],
    [ "bengkulu/lebong", "233" ],
    [ "bengkulu/mukomuko", "294" ],
    [ "bengkulu/rejang lebong", "379" ],
    [ "bengkulu/seluma", "397" ],
    [ "di yogyakarta/bantul", "39" ],
    [ "di yogyakarta/gunung kidul", "135" ],
    [ "di yogyakarta/kulon progo", "210" ],
    [ "di yogyakarta/sleman", "419" ],
    [ "di yogyakarta/yogyakarta", "501" ],
    [ "dki jakarta/jakarta barat", "151" ],
    [ "dki jakarta/jakarta pusat", "152" ],
    [ "dki jakarta/jakarta selatan", "153" ],
    [ "dki jakarta/jakarta timur", "154" ],
    [ "dki jakarta/jakarta utara", "155" ],
    [ "dki jakarta/kepulauan seribu", "189" ],
    [ "gorontalo/boalemo", "77" ],
    [ "gorontalo/bone bolango", "88" ],
    [ "gorontalo/gorontalo utara", "131" ],
    [ "gorontalo/gorontalo", "130" ],
    [ "gorontalo/pohuwato", "361" ],
    [ "jambi/batang hari", "50" ],
    [ "jambi/bungo", "97" ],
    [ "jambi/jambi", "156" ],
    [ "jambi/kerinci", "194" ],
    [ "jambi/merangin", "280" ],
    [ "jambi/muaro jambi", "293" ],
    [ "jambi/sarolangun", "393" ],
    [ "jambi/sungai penuh", "442" ],
    [ "jambi/tanjung jabung barat", "460" ],
    [ "jambi/tanjung jabung timur", "461" ],
    [ "jambi/tebo", "471" ],
    [ "jawa barat/bandung barat", "24" ],
    [ "jawa barat/bandung", "23" ],
    [ "jawa barat/banjar", "34" ],
    [ "jawa barat/bekasi", "55" ],
    [ "jawa barat/bogor", "79" ],
    [ "jawa barat/ciamis", "103" ],
    [ "jawa barat/cianjur", "104" ],
    [ "jawa barat/cimahi", "107" ],
    [ "jawa barat/cirebon", "109" ],
    [ "jawa barat/depok", "115" ],
    [ "jawa barat/garut", "126" ],
    [ "jawa barat/indramayu", "149" ],
    [ "jawa barat/karawang", "171" ],
    [ "jawa barat/kuningan", "211" ],
    [ "jawa barat/majalengka", "252" ],
    [ "jawa barat/pangandaran", "332" ],
    [ "jawa barat/purwakarta", "376" ],
    [ "jawa barat/subang", "428" ],
    [ "jawa barat/sukabumi", "431" ],
    [ "jawa barat/sumedang", "440" ],
    [ "jawa barat/tasikmalaya", "469" ],
    [ "jawa tengah/banjarnegara", "37" ],
    [ "jawa tengah/banyumas", "41" ],
    [ "jawa tengah/batang", "49" ],
    [ "jawa tengah/blora", "76" ],
    [ "jawa tengah/boyolali", "91" ],
    [ "jawa tengah/brebes", "92" ],
    [ "jawa tengah/cilacap", "105" ],
    [ "jawa tengah/demak", "113" ],
    [ "jawa tengah/grobogan", "134" ],
    [ "jawa tengah/jepara", "163" ],
    [ "jawa tengah/karanganyar", "169" ],
    [ "jawa tengah/kebumen", "177" ],
    [ "jawa tengah/kendal", "181" ],
    [ "jawa tengah/klaten", "196" ],
    [ "jawa tengah/kudus", "209" ],
    [ "jawa tengah/magelang", "250" ],
    [ "jawa tengah/pati", "344" ],
    [ "jawa tengah/pekalongan", "349" ],
    [ "jawa tengah/pemalang", "352" ],
    [ "jawa tengah/purbalingga", "375" ],
    [ "jawa tengah/purworejo", "377" ],
    [ "jawa tengah/rembang", "380" ],
    [ "jawa tengah/salatiga", "386" ],
    [ "jawa tengah/semarang", "399" ],
    [ "jawa tengah/sragen", "427" ],
    [ "jawa tengah/sukoharjo", "433" ],
    [ "jawa tengah/surakarta", "445" ],
    [ "jawa tengah/tegal", "473" ],
    [ "jawa tengah/temanggung", "476" ],
    [ "jawa tengah/wonogiri", "497" ],
    [ "jawa tengah/wonosobo", "498" ],
    [ "jawa timur/bangkalan", "31" ],
    [ "jawa timur/banyuwangi", "42" ],
    [ "jawa timur/batu", "51" ],
    [ "jawa timur/blitar", "75" ],
    [ "jawa timur/bojonegoro", "80" ],
    [ "jawa timur/bondowoso", "86" ],
    [ "jawa timur/gresik", "133" ],
    [ "jawa timur/jember", "160" ],
    [ "jawa timur/jombang", "164" ],
    [ "jawa timur/kediri", "179" ],
    [ "jawa timur/lamongan", "222" ],
    [ "jawa timur/lumajang", "243" ],
    [ "jawa timur/madiun", "248" ],
    [ "jawa timur/magetan", "251" ],
    [ "jawa timur/malang", "256" ],
    [ "jawa timur/mojokerto", "290" ],
    [ "jawa timur/nganjuk", "305" ],
    [ "jawa timur/ngawi", "306" ],
    [ "jawa timur/pacitan", "317" ],
    [ "jawa timur/pamekasan", "330" ],
    [ "jawa timur/pasuruan", "343" ],
    [ "jawa timur/ponorogo", "363" ],
    [ "jawa timur/probolinggo", "370" ],
    [ "jawa timur/sampang", "390" ],
    [ "jawa timur/sidoarjo", "409" ],
    [ "jawa timur/situbondo", "418" ],
    [ "jawa timur/sumenep", "441" ],
    [ "jawa timur/surabaya", "444" ],
    [ "jawa timur/trenggalek", "487" ],
    [ "jawa timur/tuban", "489" ],
    [ "jawa timur/tulungagung", "492" ],
    [ "kalimantan barat/bengkayang", "61" ],
    [ "kalimantan barat/kapuas hulu", "168" ],
    [ "kalimantan barat/kayong utara", "176" ],
    [ "kalimantan barat/ketapang", "195" ],
    [ "kalimantan barat/kubu raya", "208" ],
    [ "kalimantan barat/landak", "228" ],
    [ "kalimantan barat/melawi", "279" ],
    [ "kalimantan barat/pontianak", "365" ],
    [ "kalimantan barat/sambas", "388" ],
    [ "kalimantan barat/sanggau", "391" ],
    [ "kalimantan barat/sekadau", "395" ],
    [ "kalimantan barat/singkawang", "415" ],
    [ "kalimantan barat/sintang", "417" ],
    [ "kalimantan selatan/balangan", "18" ],
    [ "kalimantan selatan/banjar", "33" ],
    [ "kalimantan selatan/banjar baru", "35" ],
    [ "kalimantan selatan/banjarmasin", "36" ],
    [ "kalimantan selatan/barito kuala", "43" ],
    [ "kalimantan selatan/hulu sungai selatan", "143" ],
    [ "kalimantan selatan/hulu sungai tengah", "144" ],
    [ "kalimantan selatan/hulu sungai utara", "145" ],
    [ "kalimantan selatan/kota baru", "203" ],
    [ "kalimantan selatan/tabalong", "446" ],
    [ "kalimantan selatan/tanah bumbu", "452" ],
    [ "kalimantan selatan/tanah laut", "454" ],
    [ "kalimantan selatan/tapin", "466" ],
    [ "kalimantan tengah/barito selatan", "44" ],
    [ "kalimantan tengah/barito timur", "45" ],
    [ "kalimantan tengah/barito utara", "46" ],
    [ "kalimantan tengah/gunung mas", "136" ],
    [ "kalimantan tengah/kapuas", "167" ],
    [ "kalimantan tengah/katingan", "174" ],
    [ "kalimantan tengah/kotawaringin barat", "205" ],
    [ "kalimantan tengah/kotawaringin timur", "206" ],
    [ "kalimantan tengah/lamandau", "221" ],
    [ "kalimantan tengah/murung raya", "296" ],
    [ "kalimantan tengah/palangka raya", "326" ],
    [ "kalimantan tengah/pulang pisau", "371" ],
    [ "kalimantan tengah/seruyan", "405" ],
    [ "kalimantan tengah/sukamara", "432" ],
    [ "kalimantan timur/balikpapan", "19" ],
    [ "kalimantan timur/berau", "66" ],
    [ "kalimantan timur/bontang", "89" ],
    [ "kalimantan timur/kutai barat", "214" ],
    [ "kalimantan timur/kutai kartanegara", "215" ],
    [ "kalimantan timur/kutai timur", "216" ],
    [ "kalimantan timur/paser", "341" ],
    [ "kalimantan timur/penajam paser utara", "354" ],
    [ "kalimantan timur/samarinda", "387" ],
    [ "kalimantan utara/bulungan", "96" ],
    [ "kalimantan utara/malinau", "257" ],
    [ "kalimantan utara/nunukan", "311" ],
    [ "kalimantan utara/tana tidung", "450" ],
    [ "kalimantan utara/tarakan", "467" ],
    [ "kepulauan riau/batam", "48" ],
    [ "kepulauan riau/bintan", "71" ],
    [ "kepulauan riau/karimun", "172" ],
    [ "kepulauan riau/kepulauan anambas", "184" ],
    [ "kepulauan riau/lingga", "237" ],
    [ "kepulauan riau/natuna", "302" ],
    [ "kepulauan riau/tanjung pinang", "462" ],
    [ "lampung/bandar lampung", "21" ],
    [ "lampung/lampung barat", "223" ],
    [ "lampung/lampung selatan", "224" ],
    [ "lampung/lampung tengah", "225" ],
    [ "lampung/lampung timur", "226" ],
    [ "lampung/lampung utara", "227" ],
    [ "lampung/mesuji", "282" ],
    [ "lampung/metro", "283" ],
    [ "lampung/pesawaran", "355" ],
    [ "lampung/pesisir barat", "356" ],
    [ "lampung/pringsewu", "368" ],
    [ "lampung/tanggamus", "458" ],
    [ "lampung/tulangbawang barat", "491" ],
    [ "lampung/tulangbawang", "490" ],
    [ "lampung/way kanan", "496" ],
    [ "maluku utara/halmahera barat", "138" ],
    [ "maluku utara/halmahera selatan", "139" ],
    [ "maluku utara/halmahera tengah", "140" ],
    [ "maluku utara/halmahera timur", "141" ],
    [ "maluku utara/halmahera utara", "142" ],
    [ "maluku utara/kepulauan sula", "191" ],
    [ "maluku utara/pulau morotai", "372" ],
    [ "maluku utara/ternate", "477" ],
    [ "maluku utara/tidore kepulauan", "478" ],
    [ "maluku/ambon", "14" ],
    [ "maluku/buru selatan", "100" ],
    [ "maluku/buru", "99" ],
    [ "maluku/kepulauan aru", "185" ],
    [ "maluku/maluku barat daya", "258" ],
    [ "maluku/maluku tengah", "259" ],
    [ "maluku/maluku tenggara barat", "261" ],
    [ "maluku/maluku tenggara", "260" ],
    [ "maluku/seram bagian barat", "400" ],
    [ "maluku/seram bagian timur", "401" ],
    [ "maluku/tual", "488" ],
    [ "nusa tenggara barat/bima", "69" ],
    [ "nusa tenggara barat/dompu", "118" ],
    [ "nusa tenggara barat/lombok barat", "238" ],
    [ "nusa tenggara barat/lombok tengah", "239" ],
    [ "nusa tenggara barat/lombok timur", "240" ],
    [ "nusa tenggara barat/lombok utara", "241" ],
    [ "nusa tenggara barat/mataram", "276" ],
    [ "nusa tenggara barat/sumbawa barat", "439" ],
    [ "nusa tenggara barat/sumbawa", "438" ],
    [ "nusa tenggara timur/alor", "13" ],
    [ "nusa tenggara timur/belu", "58" ],
    [ "nusa tenggara timur/ende", "122" ],
    [ "nusa tenggara timur/flores timur", "125" ],
    [ "nusa tenggara timur/kupang", "213" ],
    [ "nusa tenggara timur/lembata", "234" ],
    [ "nusa tenggara timur/manggarai barat", "270" ],
    [ "nusa tenggara timur/manggarai timur", "271" ],
    [ "nusa tenggara timur/manggarai", "269" ],
    [ "nusa tenggara timur/nagekeo", "301" ],
    [ "nusa tenggara timur/ngada", "304" ],
    [ "nusa tenggara timur/rote ndao", "383" ],
    [ "nusa tenggara timur/sabu raijua", "385" ],
    [ "nusa tenggara timur/sikka", "412" ],
    [ "nusa tenggara timur/sumba barat daya", "435" ],
    [ "nusa tenggara timur/sumba barat", "434" ],
    [ "nusa tenggara timur/sumba tengah", "436" ],
    [ "nusa tenggara timur/sumba timur", "437" ],
    [ "nusa tenggara timur/timor tengah selatan", "479" ],
    [ "nusa tenggara timur/timor tengah utara", "480" ],
    [ "papua barat/fakfak", "124" ],
    [ "papua barat/kaimana", "165" ],
    [ "papua barat/manokwari selatan", "273" ],
    [ "papua barat/manokwari", "272" ],
    [ "papua barat/maybrat", "277" ],
    [ "papua barat/pegunungan arfak", "346" ],
    [ "papua barat/raja ampat", "378" ],
    [ "papua barat/sorong selatan", "426" ],
    [ "papua barat/sorong", "425" ],
    [ "papua barat/tambrauw", "449" ],
    [ "papua barat/teluk bintuni", "474" ],
    [ "papua barat/teluk wondama", "475" ],
    [ "papua/asmat", "16" ],
    [ "papua/biak numfor", "67" ],
    [ "papua/boven digoel", "90" ],
    [ "papua/deiyai", "111" ],
    [ "papua/dogiyai", "117" ],
    [ "papua/intan jaya", "150" ],
    [ "papua/jayapura", "158" ],
    [ "papua/jayawijaya", "159" ],
    [ "papua/keerom", "180" ],
    [ "papua/kepulauan yapen", "193" ],
    [ "papua/lanny jaya", "231" ],
    [ "papua/mamberamo raya", "263" ],
    [ "papua/mamberamo tengah", "264" ],
    [ "papua/mappi", "274" ],
    [ "papua/merauke", "281" ],
    [ "papua/mimika", "284" ],
    [ "papua/nabire", "299" ],
    [ "papua/nduga", "303" ],
    [ "papua/paniai", "335" ],
]);
